---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
data:
  CLUSTER_ID: 7dfb4fd6-5ec1-41b3-b3f6-7847b8e2838a
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ENABLE_LIMITED_CACHE: "false"
  ALLOW_CLUSTER_ACCESS: "true"
